version: '3'

networks:
    laravel:


services:
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "8000:80"
      volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      networks:
        - laravel
    mysql:
      image: mysql:5.7.22
      container_name: mysql_new
      restart: unless-stopped
      tty: true
      ports:
        - "4306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: .
        MYSQL_USER: joao_prado
        MYSQL_PASSWORD: h4g0r0m0
        MYSQL_ROOT_PASSWORD: root123
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      networks:
        - laravel
    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php_new
      volumes:
        - ./src:/var/www/html
      ports:
        - "9000:9000"
      networks:
        - laravel


